### ISSUE TITLE
Uncaught Error: Syntax error, unrecognized expression: unsupported pseudo: dev

### ISSUE THREAD

**Issue by hanifbbz** [jacogr/atom-gulp-control#14]
[Enter steps to reproduce below:]

1. Make a gulp task with colon in it `:`
2. Open gulp-control in Atom
3. Click on the task you created above

**Atom Version**: 0.201.0
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [gulp-control](https://github.com/jacogr/atom-gulp-control) package, v0.4.0

### Stack Trace

Uncaught Error: Syntax error, unrecognized expression: unsupported pseudo: dev

```
At ...atom\app-0.201.0\resources\app.asar\node_modules\jquery\dist\jquery.js:1458

Error: Syntax error, unrecognized expression: unsupported pseudo: dev
  at Function.Sizzle.error (...\atom\app-0.201.0\resources\app.asar\node_modules\jquery\dist\jquery.js:1458:8)
  at Sizzle.selectors.filter.PSEUDO (...\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\jquery\dist\jquery.js:1765:13)
  at matcherFromTokens (...\atom\app-0.201.0\resources\app.asar\node_modules\jquery\dist\jquery.js:2308:44)
  at Sizzle.compile (...\atom\app-0.201.0\resources\app.asar\node_modules\jquery\dist\jquery.js:2450:13)
  at Sizzle.select (...\atom\app-0.201.0\resources\app.asar\node_modules\jquery\dist\jquery.js:2536:16)
  at Function.Sizzle (...\atom\app-0.201.0\resources\app.asar\node_modules\jquery\dist\jquery.js:855:9)
  at GulpControlView.jQuery.fn.extend.find (...\atom\app-0.201.0\resources\app.asar\node_modules\jquery\dist\jquery.js:2695:11)
  at GulpControlView.module.exports.GulpControlView.runGulp (...\.atom\packages\gulp-control\lib\gulp-control-view.coffee:128:6)
  at space-pen-div.<anonymous> (...\packages\gulp-control\lib\gulp-control-view.coffee:30:17)
  at space-pen-div.jQuery.event.dispatch (...\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at space-pen-div.elemData.handle (...\Local\atom\app-0.201.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
     -0:50.8.0 atomatigit:show (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-light-ui)
     -0:07.5.0 gulp-control:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atomatigit, v1.5.1
gulp-control, v0.4.0

# Dev
No dev packages
```

**Comment by jacogr** [comment]
Fixed in 0.4.2
