### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by zhroeqqtw** [jacogr/atom-gulp-control#35]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.3
**System**: Mac OS X 10.11.1
**Thrown From**: [gulp-control](https://github.com/jacogr/atom-gulp-control) package, v0.4.3

### Stack Trace

Uncaught Error: spawn EACCES

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:260

Error: spawn EACCES
    at exports._errnoException (util.js:837:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:351:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:188:44)
    at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
    at GulpControlView.module.exports.GulpControlView.runGulp (/Users/dajunshi/.atom/packages/gulp-control/lib/gulp-control-view.coffee:140:20)
    at GulpControlView.module.exports.GulpControlView.getGulpTasks (/Users/dajunshi/.atom/packages/gulp-control/lib/gulp-control-view.coffee:102:6)
    at GulpControlView.module.exports.GulpControlView.initialize (/Users/dajunshi/.atom/packages/gulp-control/lib/gulp-control-view.coffee:33:6)
    at GulpControlView.View [as constructor] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at new GulpControlView (/Users/dajunshi/.atom/packages/gulp-control/lib/gulp-control-view.coffee:13:3)
    at Object.module.exports.GulpControl.newView (/Users/dajunshi/.atom/packages/gulp-control/lib/gulp-control.coffee:20:16)
    at atom-workspace.atom.commands.add.gulp-control:toggle (/Users/dajunshi/.atom/packages/gulp-control/lib/gulp-control.coffee:10:68)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1010:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
     -0:45 core:close (atom-text-editor.editor.is-focused)
     -0:02.4.0 gulp-control:toggle (textarea.)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "symbols-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.7.15
atom-ctags, v4.4.2
atom-ternjs, v0.12.2
autocomplete-paths, v1.0.2
emmet, v2.3.17
gulp-control, v0.4.3
open-recent, v4.0.1
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by DonSanto** [comment]
Suddenly I get this too. Any updates on this matter?

**Comment by neilgee** [comment]
Got it too, OSX10.11 - version 0.5.0

``` /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:262
Hide Stack Trace
Error: spawn EACCES
    at exports._errnoException (util.js:890:11)
    at ChildProcess.spawn (internal/child_process.js:302:11)
    at Object.exports.spawn (child_process.js:379:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:190:44)
    at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
    at GulpControlView.module.exports.GulpControlView.runGulp (/Users/neilg/.atom/packages/gulp-control/lib/gulp-control-view.coffee:147:20)
    at GulpControlView.module.exports.GulpControlView.getGulpTasks (/Users/neilg/.atom/packages/gulp-control/lib/gulp-control-view.coffee:109:6)
    at GulpControlView.module.exports.GulpControlView.initialize (/Users/neilg/.atom/packages/gulp-control/lib/gulp-control-view.coffee:40:6)
    at GulpControlView.View [as constructor] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/lib/space-pen.js:184:25)
    at new GulpControlView (/Users/neilg/.atom/packages/gulp-control/lib/gulp-control-view.coffee:13:3)
    at Object.module.exports.GulpControl.newView (/Users/neilg/.atom/packages/gulp-control/lib/gulp-control.coffee:20:16)
    at atom-workspace.atom.commands.add.gulp-control:toggle (/Users/neilg/.atom/packages/gulp-control/lib/gulp-control.coffee:10:68)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1109:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:329:25)
    at emitTwo (events.js:100:13)
```

installed pkgs

```
Remote-FTP@0.8.9
atom-alignment@0.12.1
atom-beautify@0.29.11
atom-wrap-in-tag@0.6.0
auto-replace-in-selection@4.0.0
autoclose-html@0.23.0
autocomplete-wordpress-hooks@0.2.0
emmet@2.4.3
genesis-snippets@2.1.0
git-plus@5.17.0
git-time-machine@1.5.3
gulp-control@0.5.0

linter@1.11.16
linter-jshint@2.1.0
linter-phpcs@1.4.0
minimap@4.25.0
monokai@0.18.0
monokai-seti@0.7.0
open-in-browser@0.4.7
open-recent@5.0.0
php-cs-fixer@2.5.9
php-debug@0.2.3
pigments@0.34.0
platformio-ide-terminal@2.2.0
seti-ui@1.3.2
split-diff@1.0.4
tabs-to-spaces@1.0.2
wp-dev@0.3.5
```

Atom 1.10.2
