### ISSUE TITLE
Error: Cannot find module '../lib/completion'

### ISSUE THREAD

**Issue by mn113** [jacogr/atom-gulp-control#46]
I have a gulpfile which is verified to be working from the command line, I have run these gulp tasks many times. As soon as I installed this package into Atom and clicked Packages > gulp-control > Open, it errored and spewed out the following:

```
Retrieving list of gulp tasks
module.js:327
    throw err;
    ^
Error: Cannot find module '../lib/completion'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object. (~/mydir/node_modules/.bin/gulp:13:18)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:429:10)
Exited with code 1
```
I'm not sure why a module would be missing. I have node installed globally in the default /usr/local/bin and gulp and its dependencies installed locally.

**Comment by karthikeyana** [comment]
the issue in gulp module, so uninstall and install the gulp module 
$ `npm uninstall gulp --save`
$ `npm install gulp --save`
