### ISSUE TITLE
Uncaught Error: Syntax error, unrecognized expression: unsupported pseudo: front

### ISSUE THREAD

**Issue by amitmtrn** [jacogr/atom-gulp-control#5]
steps to reproduce below:

1. create Gulpfile.js
2. add task name "serve:front"
3. try to run that task with gulp control

**Atom Version**: 0.179.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [gulp-control](https://github.com/jacogr/atom-gulp-control) package, v0.3.3

### Stack Trace

Uncaught Error: Syntax error, unrecognized expression: unsupported pseudo: front

```
At C:\Users\amitmtrn\AppData\Local\atom\app-0.179.0\resources\app\node_modules\space-pen\vendor\jquery.js:1715

Error: Syntax error, unrecognized expression: unsupported pseudo: front
  at Function.Sizzle.error (C:\Users\amitmtrn\AppData\Local\atom\app-0.179.0\resources\app\node_modules\space-pen\vendor\jquery.js:1715:8)
  at Sizzle.selectors.filter.PSEUDO (C:\Users\amitmtrn\AppData\Local\atom\app-0.179.0\resources\app\node_modules\space-pen\vendor\jquery.js:2018:13)
  at matcherFromTokens (C:\Users\amitmtrn\AppData\Local\atom\app-0.179.0\resources\app\node_modules\space-pen\vendor\jquery.js:2543:44)
  at Sizzle.compile (C:\Users\amitmtrn\AppData\Local\atom\app-0.179.0\resources\app\node_modules\space-pen\vendor\jquery.js:2687:13)
  at select (C:\Users\amitmtrn\AppData\Local\atom\app-0.179.0\resources\app\node_modules\space-pen\vendor\jquery.js:2764:2)
  at Function.Sizzle (C:\Users\amitmtrn\AppData\Local\atom\app-0.179.0\resources\app\node_modules\space-pen\vendor\jquery.js:1154:9)
  at GulpControlView.jQuery.fn.extend.find (C:\Users\amitmtrn\AppData\Local\atom\app-0.179.0\resources\app\node_modules\space-pen\vendor\jquery.js:5163:11)
  at GulpControlView.module.exports.GulpControlView.runGulp (C:\Users\amitmtrn\.atom\packages\gulp-control\lib\gulp-control-view.coffee:119:6)
  at HTMLDivElement.<anonymous> (C:\Users\amitmtrn\.atom\packages\gulp-control\lib\gulp-control-view.coffee:28:17)
  at HTMLDivElement.handler (C:\Users\amitmtrn\AppData\Local\atom\app-0.179.0\resources\app\src\space-pen-extensions.js:112:34)
  at HTMLDivElement.jQuery.event.dispatch (C:\Users\amitmtrn\AppData\Local\atom\app-0.179.0\resources\app\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDivElement.elemData.handle (C:\Users\amitmtrn\AppData\Local\atom\app-0.179.0\resources\app\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
     -1:00.0 application:open-folder (atom-text-editor.editor)
     -0:58.3 command-palette:toggle (atom-text-editor.editor)
     -0:56.6 core:confirm (atom-text-editor.editor.mini)
     -0:56.5 gulp-control:toggle (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-objective-c",
      "language-c",
      "language-csharp",
      "welcome",
      "jshint",
      "script"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.1.6
emmet, v2.3.3
gulp-control, v0.3.3
linter, v0.11.1
linter-jscs, v1.5.0
linter-jshint, v0.1.0

# Dev
No dev packages
```

**Comment by jacogr** [comment]
Fixed in 0.4.2
